import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { execa } from 'execa';
import { describe, test, expect, beforeEach } from 'vitest';

/**
 *
 * @param task
 */
function getName(task) {
	return encodeURIComponent(`${task.suite.name}_${task.name}`.toLowerCase());
}

beforeEach((ctx) => {
	ctx.tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'test-'));
});

describe('CLI', () => {
	/**
	 *
	 * @param dir
	 * @param type
	 */
	async function cliTest(dir, type) {
		const { stdout } = await execa(
			'npx',
			[
				'@d-zero/create-frontend',
				...(type ? ['--type', type] : []),
				'--dir',
				dir,
				'--no-install',
				'--silent',
			],
			{
				failed: true,
				env: {
					NODE_NO_WARNINGS: '1',
				},
			},
		);
		return stdout.replaceAll(path.sep, '/').split('\n');
	}

	test('npx', async ({ tmpDir, task }) => {
		const dir = path.join(tmpDir, getName(task));
		const actual = await cliTest(dir);
		expect(actual).toStrictEqual([
			`✔  ++ ${dir}/tsconfig.json`,
			`✔  ++ ${dir}/prh.yaml`,
			`✔  ++ ${dir}/package.json`,
			`✔  ++ ${dir}/markuplint.config.js`,
			`✔  ++ ${dir}/lint-staged.config.mjs`,
			`✔  ++ ${dir}/eslint.config.js`,
			`✔  ++ ${dir}/eleventy.config.mjs`,
			`✔  ++ ${dir}/cspell.json`,
			`✔  ++ ${dir}/burgereditor.config.js`,
			`✔  ++ ${dir}/README.md`,
			`✔  ++ ${dir}/CHANGELOG.md`,
			`✔  ++ ${dir}/.yarnrc.yml`,
			`✔  ++ ${dir}/.textlintrc.js`,
			`✔  ++ ${dir}/.textlintignore`,
			`✔  ++ ${dir}/.stylelintrc`,
			`✔  ++ ${dir}/.pug-lintrc`,
			`✔  ++ ${dir}/.prettierrc.mjs`,
			`✔  ++ ${dir}/.postcssrc.js`,
			`✔  ++ ${dir}/.npmignore`,
			`✔  ++ ${dir}/.gitignore`,
			`✔  ++ ${dir}/.editorconfig`,
			`✔  ++ ${dir}/.clinerules`,
			`✔  ++ ${dir}/.clineignore`,
			`✔  ++ ${dir}/htdocs/files/images/sample.png`,
			`✔  ++ ${dir}/ai-tasks/page-to-burger.md`,
			`✔  ++ ${dir}/ai-tasks/create-page.md`,
			`✔  ++ ${dir}/ai-tasks/create-component.md`,
			`✔  ++ ${dir}/__info/print.txt`,
			`✔  ++ ${dir}/__assets/htdocs/index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/sample/index.html`,
			`✔  ++ ${dir}/__assets/htdocs/js/script.ts`,
			`✔  ++ ${dir}/__assets/htdocs/css/style.css`,
			`✔  ++ ${dir}/__assets/htdocs/css/bge_style.css`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/302_form_complete.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/302_form_complete.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/301_form_confirm.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/301_form_confirm.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/300_form_input.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/300_form_input.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/210_blog_index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/210_blog_index.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/200_blog_index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/200_blog_index.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/100_sub.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/100_sub.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/000_home.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/000_home.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/style/general/img.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/button.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/body.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/all.css`,
			`✔  ++ ${dir}/__assets/_libs/style/base/root.css`,
			`✔  ++ ${dir}/__assets/_libs/script/index.ts`,
			`✔  ++ ${dir}/__assets/_libs/mixin/meta.pug`,
			`✔  ++ ${dir}/__assets/_libs/layouts/sub.pug`,
			`✔  ++ ${dir}/__assets/_libs/layouts/home.pug`,
			`✔  ++ ${dir}/__assets/_libs/img/bg-repeat-01.gif`,
			`✔  ++ ${dir}/__assets/_libs/img/bg-arrow.svg`,
			`✔  ++ ${dir}/__assets/_libs/data/data.yml`,
			`✔  ++ ${dir}/__assets/_libs/data/blocks.js`,
			`✔  ++ ${dir}/__assets/_libs/data/blocks.html`,
			`✔  ++ ${dir}/__assets/_libs/data/bge-blocks.html`,
			`✔  ++ ${dir}/__assets/_libs/data/bge-blocks-v2.html`,
			`✔  ++ ${dir}/__assets/_libs/data/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/component/c-title-page.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-title-page.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-pagination.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-pagination.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-page-sub.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-page-home.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-sitemap.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-sitemap.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-global.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-global.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-breadcrumb.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-breadcrumb.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media-list.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-header.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-header.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-footer.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-footer.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-content-main.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-content-index.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card-list.css`,
			`✔  ++ ${dir}/.vscode/settings.json`,
			`✔  ++ ${dir}/.vscode/extensions.json`,
			`✔  ++ ${dir}/.husky/pre-commit`,
			'✔  Install dependencies : skipped',
		]);
	});

	test('npx --type burger', async ({ tmpDir, task }) => {
		const dir = path.join(tmpDir, getName(task));
		const actual = await cliTest(dir, 'burger');
		expect(actual).toStrictEqual([
			`✔  ++ ${dir}/tsconfig.json`,
			`✔  ++ ${dir}/prh.yaml`,
			`✔  ++ ${dir}/package.json`,
			`✔  ++ ${dir}/markuplint.config.js`,
			`✔  ++ ${dir}/lint-staged.config.mjs`,
			`✔  ++ ${dir}/eslint.config.js`,
			`✔  ++ ${dir}/eleventy.config.mjs`,
			`✔  ++ ${dir}/cspell.json`,
			`✔  ++ ${dir}/burgereditor.config.js`,
			`✔  ++ ${dir}/README.md`,
			`✔  ++ ${dir}/CHANGELOG.md`,
			`✔  ++ ${dir}/.yarnrc.yml`,
			`✔  ++ ${dir}/.textlintrc.js`,
			`✔  ++ ${dir}/.textlintignore`,
			`✔  ++ ${dir}/.stylelintrc`,
			`✔  ++ ${dir}/.pug-lintrc`,
			`✔  ++ ${dir}/.prettierrc.mjs`,
			`✔  ++ ${dir}/.postcssrc.js`,
			`✔  ++ ${dir}/.npmignore`,
			`✔  ++ ${dir}/.gitignore`,
			`✔  ++ ${dir}/.editorconfig`,
			`✔  ++ ${dir}/.clinerules`,
			`✔  ++ ${dir}/.clineignore`,
			`✔  ++ ${dir}/htdocs/files/images/sample.png`,
			`✔  ++ ${dir}/ai-tasks/page-to-burger.md`,
			`✔  ++ ${dir}/ai-tasks/create-page.md`,
			`✔  ++ ${dir}/ai-tasks/create-component.md`,
			`✔  ++ ${dir}/__info/print.txt`,
			`✔  ++ ${dir}/__assets/htdocs/index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/sample/index.html`,
			`✔  ++ ${dir}/__assets/htdocs/js/script.ts`,
			`✔  ++ ${dir}/__assets/htdocs/css/style.css`,
			`✔  ++ ${dir}/__assets/htdocs/css/bge_style.css`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/302_form_complete.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/302_form_complete.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/301_form_confirm.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/301_form_confirm.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/300_form_input.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/300_form_input.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/210_blog_index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/210_blog_index.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/200_blog_index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/200_blog_index.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/100_sub.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/100_sub.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/000_home.pug`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/000_home.json`,
			`✔  ++ ${dir}/__assets/htdocs/__tmpl/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/style/general/img.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/button.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/body.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/all.css`,
			`✔  ++ ${dir}/__assets/_libs/style/base/root.css`,
			`✔  ++ ${dir}/__assets/_libs/script/index.ts`,
			`✔  ++ ${dir}/__assets/_libs/mixin/meta.pug`,
			`✔  ++ ${dir}/__assets/_libs/layouts/sub.pug`,
			`✔  ++ ${dir}/__assets/_libs/layouts/home.pug`,
			`✔  ++ ${dir}/__assets/_libs/img/bg-repeat-01.gif`,
			`✔  ++ ${dir}/__assets/_libs/img/bg-arrow.svg`,
			`✔  ++ ${dir}/__assets/_libs/data/data.yml`,
			`✔  ++ ${dir}/__assets/_libs/data/blocks.js`,
			`✔  ++ ${dir}/__assets/_libs/data/blocks.html`,
			`✔  ++ ${dir}/__assets/_libs/data/bge-blocks.html`,
			`✔  ++ ${dir}/__assets/_libs/data/bge-blocks-v2.html`,
			`✔  ++ ${dir}/__assets/_libs/data/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/component/c-title-page.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-title-page.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-pagination.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-pagination.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-page-sub.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-page-home.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-sitemap.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-sitemap.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-global.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-global.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-breadcrumb.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-breadcrumb.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media-list.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-header.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-header.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-footer.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-footer.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-content-main.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-content-index.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card-list.css`,
			`✔  ++ ${dir}/.vscode/settings.json`,
			`✔  ++ ${dir}/.vscode/extensions.json`,
			`✔  ++ ${dir}/.husky/pre-commit`,
			'✔  Install dependencies : skipped',
		]);
	});

	test('npx --type static', async ({ tmpDir, task }) => {
		const dir = path.join(tmpDir, getName(task));
		const actual = await cliTest(dir, 'static');
		expect(actual).toStrictEqual([
			`✔  ++ ${dir}/tsconfig.json`,
			`✔  ++ ${dir}/prh.yaml`,
			`✔  ++ ${dir}/package.json`,
			`✔  ++ ${dir}/markuplint.config.js`,
			`✔  ++ ${dir}/lint-staged.config.mjs`,
			`✔  ++ ${dir}/eslint.config.js`,
			`✔  ++ ${dir}/eleventy.config.mjs`,
			`✔  ++ ${dir}/cspell.json`,
			`✔  ++ ${dir}/burgereditor.config.js`,
			`✔  ++ ${dir}/README.md`,
			`✔  ++ ${dir}/CHANGELOG.md`,
			`✔  ++ ${dir}/.yarnrc.yml`,
			`✔  ++ ${dir}/.textlintrc.js`,
			`✔  ++ ${dir}/.textlintignore`,
			`✔  ++ ${dir}/.stylelintrc`,
			`✔  ++ ${dir}/.pug-lintrc`,
			`✔  ++ ${dir}/.prettierrc.mjs`,
			`✔  ++ ${dir}/.postcssrc.js`,
			`✔  ++ ${dir}/.npmignore`,
			`✔  ++ ${dir}/.gitignore`,
			`✔  ++ ${dir}/.editorconfig`,
			`✔  ++ ${dir}/.clinerules`,
			`✔  ++ ${dir}/.clineignore`,
			`✔  ++ ${dir}/htdocs/files/images/sample.png`,
			`✔  ++ ${dir}/ai-tasks/page-to-burger.md`,
			`✔  ++ ${dir}/ai-tasks/create-page.md`,
			`✔  ++ ${dir}/ai-tasks/create-component.md`,
			`✔  ++ ${dir}/__info/print.txt`,
			`✔  ++ ${dir}/__assets/htdocs/index.pug`,
			`✔  ++ ${dir}/__assets/htdocs/sample/index.html`,
			`✔  ++ ${dir}/__assets/htdocs/js/script.ts`,
			`✔  ++ ${dir}/__assets/htdocs/css/style.css`,
			`✔  ++ ${dir}/__assets/_libs/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/style/general/img.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/button.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/body.css`,
			`✔  ++ ${dir}/__assets/_libs/style/general/all.css`,
			`✔  ++ ${dir}/__assets/_libs/style/base/root.css`,
			`✔  ++ ${dir}/__assets/_libs/script/index.ts`,
			`✔  ++ ${dir}/__assets/_libs/mixin/meta.pug`,
			`✔  ++ ${dir}/__assets/_libs/layouts/sub.pug`,
			`✔  ++ ${dir}/__assets/_libs/layouts/home.pug`,
			`✔  ++ ${dir}/__assets/_libs/img/bg-repeat-01.gif`,
			`✔  ++ ${dir}/__assets/_libs/img/bg-arrow.svg`,
			`✔  ++ ${dir}/__assets/_libs/data/data.yml`,
			`✔  ++ ${dir}/__assets/_libs/data/blocks.js`,
			`✔  ++ ${dir}/__assets/_libs/data/blocks.html`,
			`✔  ++ ${dir}/__assets/_libs/data/.markuplintrc`,
			`✔  ++ ${dir}/__assets/_libs/component/c-title-page.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-title-page.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-pagination.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-pagination.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-page-sub.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-page-home.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-sitemap.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-sitemap.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-global.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-global.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-breadcrumb.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-nav-breadcrumb.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-media-list.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-header.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-header.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-footer.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-footer.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-content-main.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-content-index.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card.pug`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card.css`,
			`✔  ++ ${dir}/__assets/_libs/component/c-card-list.css`,
			`✔  ++ ${dir}/.vscode/settings.json`,
			`✔  ++ ${dir}/.vscode/extensions.json`,
			`✔  ++ ${dir}/.husky/pre-commit`,
			'✔  Install dependencies : skipped',
		]);
	});
});
