name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-latest
          # - windows-latest
        node: [22]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        id: cache-depends
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4
        with:
          path: '**/node_modules'
          key: os-${{ matrix.os }}-node${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - name: Create .yarnrc for Windows
        if: runner.os == 'Windows' && steps.cache-depends.outputs.cache-hit != 'true'
        run: echo "network-timeout 600000" > .yarnrc

      - name: Install dependencies
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --check-files

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
