name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-latest
          # - windows-latest
        node: [22]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        id: cache-depends
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          path: '**/node_modules'
          key: os-${{ matrix.os }}-node${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - name: Create .yarnrc for Windows
        if: runner.os == 'Windows' && steps.cache-depends.outputs.cache-hit != 'true'
        run: echo "network-timeout 600000" > .yarnrc

      - name: Install dependencies
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --check-files

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
