name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-latest
          # - windows-latest
        node: [24]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack and setup Yarn v4
        run: |
          corepack enable
          yarn --version

      - name: Cache dependencies
        id: cache-depends
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: '**/node_modules'
          key: os-${{ matrix.os }}-node${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - name: Create .yarnrc for Windows
        if: runner.os == 'Windows' && steps.cache-depends.outputs.cache-hit != 'true'
        run: echo "network-timeout 600000" > .yarnrc

      - name: Install dependencies for Renovate/Dependabot
        if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
        run: yarn install --refresh-lockfile

      - name: Install dependencies for normal PRs
        if: github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]'
        run: yarn install --immutable

      - name: Compile
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
